package:
  name: uqcme
  version: 0.2.0

source:
  path: .

build:
  noarch: python
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.12
    - pip >=24.0
    - setuptools >=69.0
    - wheel >=0.42
  run:
    - streamlit >=1.47.1,<2
    - pandas >=2.3.1,<3
    - plotly >=6.2.0,<7
    - pyyaml >=6.0.2,<7
    - openpyxl >=3.1.5,<4
    - pydantic >=2.12.4,<3
    - pandera >=0.26.1,<0.27.0

about:
  summary: A quality control dashboard for sequencing data
  license: MIT
  license_file: LICENSE
