package:
  name: uqcme
  version: 0.6.0  # Update this to match __init__.py version

build:
  noarch: python
  script: pip install uqcme[all]==${PKG_VERSION} --no-deps

requirements:
  host:
    - python >=3.12,<3.13
    - pip
  run:
    - python >=3.12,<3.13
    - pip
    # All Python dependencies are handled by pip from PyPI

about:
  summary: A quality control dashboard for sequencing data (installed from PyPI)
  license: MIT
  license_file: LICENSE
