{% set name = "uqcme" %}
{% set data = load_file_regex(load_file=RECIPE_DIR + "/../src/uQCme/__init__.py", regex_pattern="__version__\\s*=\\s*['\"]([^'\"]+)['\"]") %}
{% set version = data.group(1) %}


package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script: pip install {{ name }}[all]=={{ version }} --no-deps

requirements:
  host:
    - python >=3.12,<3.13
    - pip
  run:
    - python >=3.12,<3.13
    - pip
    # Core dependencies (installed via pip from PyPI)
    # The package and its Python dependencies come from PyPI

test:
  imports:
    - uQCme
  commands:
    - uqcme --help
    - uqcme-dashboard --help

about:
  home: https://github.com/ssi-dk/uQCme
  license: MIT
  license_file: LICENSE
  summary: Microbial Quality Control Dashboard
  description: |
    A comprehensive quality control (QC) tool for microbial sequencing data
    that provides both command-line processing and interactive web-based
    visualization capabilities.
    
    This conda package installs uqcme from PyPI.
  dev_url: https://github.com/ssi-dk/uQCme

extra:
  recipe-maintainers:
    - kimleeng
