{% set name = "uqcme" %}
{% set data = load_file_regex(load_file=RECIPE_DIR + "/../src/uqcme/__init__.py", regex_pattern="__version__\\s*=\\s*['\"]([^'\"]+)['\"]") %}
{% set version = data.group(1) %}


package:
  name: uqcme
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - uqcme = uQCme.cli.main:main
    - uqcme-dashboard = uQCme.app.main:main

requirements:
  host:
    - python >=3.12,<3.13
    - pip
    - setuptools >=61.0
  run:
    - python >=3.12,<3.13
    - streamlit >=1.28.0
    - pandas >=1.5.0
    - plotly >=5.15.0
    - pyyaml >=6.0
    - openpyxl >=3.0.0
    - pydantic >=2.0.0
    - pandera >=0.18.0

test:
  imports:
    - uQCme
  commands:
    - uqcme --help
    - uqcme-dashboard --help

about:
  home: https://github.com/ssi-dk/uQCme
  license: MIT
  license_file: LICENSE
  summary: Microbial Quality Control Dashboard
  description: |
    A comprehensive quality control (QC) tool for microbial sequencing data
    that provides both command-line processing and interactive web-based
    visualization capabilities.
  dev_url: https://github.com/ssi-dk/uQCme

extra:
  recipe-maintainers:
    - kimleeng
