{% set name = "uqcme" %}
{% set data = load_file_regex(load_file=RECIPE_DIR + "/../src/uQCme/__init__.py", regex_pattern="__version__\\s*=\\s*['\"]([^'\"]+)['\"]") %}
{% set version = data.group(1) %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: pip install .[all] -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.12,<3.13
    - pip
    - hatchling
  run:
    - python >=3.12,<3.13
    # Core dependencies
    - pandas >=1.5.0
    - pyyaml >=6.0
    - pydantic >=2.0.0
    - pandera >=0.18.0
    # App dependencies
    - streamlit >=1.28.0
    - plotly >=5.15.0
    - openpyxl >=3.0.0

test:
  imports:
    - uQCme
  commands:
    - uqcme --help
    - uqcme-dashboard --help

about:
  home: https://github.com/ssi-dk/uQCme
  license: MIT
  license_file: LICENSE
  summary: Microbial Quality Control Dashboard
  description: |
    A comprehensive quality control (QC) tool for microbial sequencing data
    that provides both command-line processing and interactive web-based
    visualization capabilities.
  dev_url: https://github.com/ssi-dk/uQCme

extra:
  recipe-maintainers:
    - kimleeng
